### ISSUE TITLE
Add a public directory for the web root

### ISSUE THREAD

**Issue by shrink** [asika32764/natika#11]
The web root for a project should be a safe directory, one that contains only whitelisted files for public access, any file that should not be accessible via the web should not be present in the web root. This project depends on the `.htaccess` files in various directories for security, which means a misconfigured web server can expose sensitive information, or if someone is using a different webserver (such as nginx) they must manually blacklist each sensitive endpoint.

For example http://natika.windwalker.io/composer.json or on a misconfigured server this file might be accessible http://natika.windwalker.io/etc/secret.yml

The most common approach to this problem is to have a directory called `public` which serves as the web root, then inside the `public` directory you have index.php which references a bootstrap file outside of the web root. As long as the web root is correctly set as `public` then only files in `public` will be accessible, meaning your project files will be secure by default on all web servers, not just ones that support `.htaccess`.

An example of this strategy is available in the Laravel framework here: https://github.com/laravel/laravel

**Comment by asika32764** [comment]
By default, Windwalker framework has a public web dir, see: https://github.com/ventoviro/windwalker-starter/tree/master/www

I moved index.php to root for some users who may need natika runs on share hosting.

If someone wants be more security, simply create a `/public` folder and move these files and dirs into it:
- `index.php`
- `dev.php`
- `.htaccess`
- `web.config`
- `robots.txt`
- `/media`

Then modify `/etc/define.php` to add `/public` folder on `WINDWALKER_PUBLIC`.

I think I can write a simple manual to help users do this.
