### ISSUE TITLE
php natika create-user: Wrong fields

### ISSUE THREAD

**Issue by PanamaCityPC** [asika32764/natika#14]
php natika create-user prompts for various information. At the end, outputs:

> User with username <strong>[the email I entered]</strong> is not available.

I have checked, and I supplied my email for the prompt "Email:", not "username:"

Trying to supply a username into the "Email:" prompt say it's not a valid email (unsurprisingly, since it's not a valid email).

Thus, I cannot create a user.

**Comment by PanamaCityPC** [comment]
Also: I installed via composer; the setup prompted me to create a user. It didn't give any error, but I cannot log in using the supplied information.

**Comment by asika32764** [comment]
I think this issue cause is that you entered an email or username which has been exists in the fake data (If you installed fake data).

I can successfully create user.

![p-2016-04-05-004](https://cloud.githubusercontent.com/assets/1639206/14273637/aab983ba-fb3e-11e5-8604-8d424a505ea0.jpg)

I guess this message is just print wrong language translation.

> User with username [the email I entered] is not available.

Could you try re-create a new user without fake data?

Simply run 

```
php natika seed clear
php natika create-user
```

**Comment by PanamaCityPC** [comment]
Awesome, thank you very much. It did work. :)
